server:
  port: 8080

spring:
  application:
    name: customer-products-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cp_service
    username: cp_service_user
    password: qwerty$4
