server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: customer-products-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cp_service
    username: cp_service_user
    password: qwerty$4
  liquibase:
    enabled: true
    default-schema: public
    change-log: classpath:db/liquibase-changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
